mkfifo "$XDG_RUNTIME_DIR"/xob_vol &
setxkbmap pl -variant colemak -option caps:swapescape &
xrdb -merge "$XDG_CONFIG_HOME/x11/Xresources" &
pipewire &
pipewire-pulse &
hsetroot -cover "$XDG_DATA_HOME/wall.jpg" &
picom -b &
batsignal -b -w 25 -c 10 -d 5 &
tail -f "$XDG_RUNTIME_DIR"/xob_vol | xob &
unclutter -b &
exec dbus-run-session herbstluftwm

