#!/bin/sh
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:="$HOME/.config"}"
export XDG_DATA_HOME="${XDG_DATA_HOME:="$HOME/.local/share"}"
path="$HOME/.dotfiles"

ln -sf "$path/.mkshrc" "$HOME/.mkshrc"
ln -sf "$path/.profile" "$HOME/.profile"

[ ! -d "$XDG_CONFIG_HOME" ] && mkdir "$XDG_CONFIG_HOME"

ln -sf "$path/.config/aliasrc" "$XDG_CONFIG_HOME/aliasrc"
ln -sf "$path/.config/wgetrc" "$XDG_CONFIG_HOME/wgetrc"

[ ! -d "$XDG_CONFIG_HOME/mksh" ] && mkdir "$XDG_CONFIG_HOME/mksh"
ln -sf "$path/.config/mksh/completion.mksh" "$XDG_CONFIG_HOME/mksh/completion.mksh"
ln -sf "$path/.config/mksh/key-bindings.mksh" "$XDG_CONFIG_HOME/mksh/key-bindings.mksh"
ln -sf "$path/.config/mksh/utils.mksh" "$XDG_CONFIG_HOME/mksh/utils.mksh"

[ ! -d "$XDG_CONFIG_HOME/fontconfig" ] && mkdir "$XDG_CONFIG_HOME/fontconfig"
ln -sf "$path/.config/fontconfig/fonts.conf" "$XDG_CONFIG_HOME/fontconfig/fonts.conf"

[ ! -d "$XDG_CONFIG_HOME/gtk-2.0" ] && mkdir "$XDG_CONFIG_HOME/gtk-2.0"
ln -sf "$path/.config/gtk-2.0/gtkrc" "$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

[ ! -d "$XDG_CONFIG_HOME/gtk-3.0" ] && mkdir "$XDG_CONFIG_HOME/gtk-3.0"
ln -sf "$path/.config/gtk-3.0/settings.ini" "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"

[ -d "$XDG_CONFIG_HOME/nvim" ] && rm -rf "$XDG_CONFIG_HOME/nvim"
ln -sf "$path/.config/nvim" "$XDG_CONFIG_HOME/nvim"

[ ! -d "$XDG_CONFIG_HOME/readline" ] && mkdir "$XDG_CONFIG_HOME/readline"
ln -sf "$path/.config/readline/inputrc" "$XDG_CONFIG_HOME/readline/inputrc"

[ ! -d "$XDG_CONFIG_HOME/mpv" ] && mkdir "$XDG_CONFIG_HOME/mpv"
[ ! -d "$XDG_CONFIG_HOME/mpv/scripts" ] && mkdir "$XDG_CONFIG_HOME/mpv/scripts"
ln -sf "$path/.config/mpv/mpv.conf" "$XDG_CONFIG_HOME/mpv/mpv.conf"
ln -sf "$path/.config/mpv/scripts/copy-permalink.lua" "$XDG_CONFIG_HOME/mpv/scripts/copy-permalink.lua"
ln -sf "$path/.config/mpv/scripts/autosubsync" "$XDG_CONFIG_HOME/mpv/scripts/autosubsync"

[ ! -d "$XDG_CONFIG_HOME/newsboat" ] && mkdir "$XDG_CONFIG_HOME/newsboat"
ln -sf "$path/.config/newsboat/config" "$XDG_CONFIG_HOME/newsboat/config"

[ ! -d "$XDG_CONFIG_HOME/ytfzf" ] && mkdir "$XDG_CONFIG_HOME/ytfzf"
ln -sf "$path/.config/ytfzf/conf.sh" "$XDG_CONFIG_HOME/ytfzf/conf.sh"
