= Dotfiles
chtc <notnotcha0t1c@protonmail.com>
{docdate}
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

IMPORTANT: I'm currently using Fedora, go to tag https://github.com/notchtc/dotfiles/tree/waldluft[waldluft] for the full rice (the files for the other software still stay in this repo because I'm lazy).

These are my very horrible dotfiles.

Older rices are in the https://github.com/notchtc/dotfiles-old[dotfiles-old repository].

== Used
[horizontal]
OS:: https://voidlinux.org[fedora linux]
Shell:: https://www.mirbsd.org/mksh.htm[mksh] (link:./.mkshrc[config is here])
Text Editor:: https://neovim.io[neovim] (link:./.config/nvim[config is here])
Media Player:: https://mpv.io[mpv] (link:./.config/mpv[config is here])
Browser:: https://fanglingsu.github.io/vimb[firefox]
Music Player:: https://wiki.gnome.org/Apps/Lollypop[lollypop]
GTK3 Theme:: https://github.com/lassekongo83/adw-gtk3[adw-gtk3]
Font(s):: https://github.com/be5invis/Iosevka/[iosevka] (Default, Term and Aile)

== How to install
[WARNING]
====
This will replace your existing configuration!

If you want only some of the configs, copy them to the appropriate directory.
====

1. Install dependencies
2. Clone the repository
[source,shell]
git clone --recurse-submodules https://github.com/notchtc/dotfiles.git "$HOME"/.dotfiles
3. Enter the dotfiles directory.
[source,shell]
cd "$HOME"/.dotfiles
4. Run the install-fedora script.
