= Dotfiles
chtc <notnotcha0t1c@protonmail.com>
{docdate}
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

These are my very horrible dotfiles.

Older rices are in the https://github.com/notchtc/dotfiles-old[dotfiles-old repository].

== Used
[horizontal]
OS:: https://voidlinux.org[void linux]
Shell:: https://www.mirbsd.org/mksh.htm[mksh] (link:./.mkshrc[config is here])
WM:: https://herbstluftwm.org[herbstluftwm] (link:./.config/herbstluftwm[config is here])
Bar:: https://polybar.github.io/[polybar] (link:./.config/polybar[config is here])
Application Launcher:: https://github.com/davatorium/rofi[rofi] (link:./.config/rofi[config is here])
Compositor:: https://github.com/yshui/picom[picom] (link:./.config/picom.conf[config is here])
Screen Locker:: https://github.com/notchtc/slock[slock]
Wallpaper Setter:: https://github.com/himdel/hsetroot[hsetroot]
Terminal:: https://github.com/endaaman/tym[tym]
Text Editor:: https://neovim.io[neovim] (link:./.config/nvim[config is here])
Music Player:: https://cmus.github.io[cmus] (link:./.config/cmus/rc[config is here])
Media Player:: https://mpv.io[mpv] (link:./.config/mpv[config is here])
Image Viewer:: https://github.com/nsxiv/nsxiv[nsxiv] (link:./.config/nsxiv/exec[config is here])
PDF Reader:: https://pwmt.org/projects/zathura/[zathura] (link:./.config/zathura/zathurarc[config is here])
Browser:: https://fanglingsu.github.io/vimb[vimb] (link:./.config/vimb/[config is here]) + https://github.com/notchtc/tabbed[tabbed] (for tabs)
IRC Client:: https://irssi.org[irssi] (link:./.local/share/irssi/default.theme[config is here])
Notification Daemon:: https://github.com/dunst-project/dunst[dunst] (link:./.config/dunst/dunstrc[config is here])
Font(s):: https://github.com/be5invis/Iosevka/[iosevka] (Default, Term and Aile) & https://github.com/ryanoasis/nerd-fonts[iosevka nerd font] & noto fonts emoji
Colorscheme:: https://github.com/jcornwall/base16-woodland-scheme[base16-woodland]

Here is a full list of everything (stuff that either has a config or is used somewhere) that wasn't mentioned previously:

- asciidoctor & asciidoctor-pdf
- dbus-launch
- doas
- hsetroot
- notify-send
- pipewire & pipewire-pulse
- trash-cli
- wget
- xprop
- yt-dlp

== How to install
[WARNING]
====
This will replace your existing configuration!

If you want only some of the configs, copy them to the appropriate directory.
====

1. Install dependencies
2. Clone the repository
[source,shell]
git clone --recurse-submodules https://github.com/notchtc/dotfiles.git "$HOME"/.dotfiles
3. Enter the dotfiles directory.
[source,shell]
cd "$HOME"/.dotfiles
4. Run the install script.
