= Dotfiles
chtc <notnotcha0t1c@protonmail.com>
{docdate}

These are my very horrible dotfiles.

Older rices are in the https://github.com/notchtc/dotfiles-old[dotfiles-old repository].

== Used
[horizontal]
OS:: https://voidlinux.org[void linux]
Shell:: https://www.mirbsd.org/mksh.htm[mksh]
WM:: https://herbstluftwm.org[herbstluftwm]
Bar:: https://polybar.github.io/[polybar]
Screen Locker:: https://github.com/notchtc/slock[slock]
Wallpaper Setter:: https://github.com/himdel/hsetroot[hsetroot]
Terminal:: https://github.com/notchtc/st[st] or https://codeberg.org/dnkl/foot[foot] when on wayland
Text Editor:: https://neovim.io[neovim]
Music Player:: https://cmus.github.io[cmus]
Media Player:: https://mpv.io[mpv]
Image Viewer:: https://sr.ht/~exec64/imv/[imv]
PDF Reader:: https://pwmt.org/projects/zathura/[zathura]
Browser:: https://www.mozilla.org/en-US/firefox/new[firefox]
Notification Daemon:: https://github.com/dunst-project/dunst[dunst]
Font(s):: https://github.com/be5invis/Iosevka/[iosevka] (Default, Term and Aile) & https://github.com/ryanoasis/nerd-fonts[iosevka nerd font] & noto fonts emoji
Colorscheme:: https://github.com/ishan9299/nvim-solarized-lua[solarized]

Here is a full list of everything (stuff that either has a config or is used somewhere) that wasn't mentioned previously:

- adwaita++
- asciidoctor & asciidoctor-pdf
- connman-ui-gtk
- dbus-launch
- doas
- hsetroot
- notify-send
- pipewire & pipewire-pulse
- https://github.com/Ferdi265/numix-solarized-gtk-theme[numix-solarized-gtk-theme] (dark yellow variant)
- trash-cli
- unclutter
- wget
- xprop
- yt-dlp

== How to install
1. Install dependencies
2. Clone the repository
[source,shell]
git clone https://github.com/notchtc/dotfiles.git "$HOME"/.dotfiles
3. Enter the dotfiles directory.
[source,shell]
cd "$HOME"/.dotfiles
4. Run the install script.
