#!/bin/sh

# editor
alias e="$EDITOR"
alias se="sudo -E $EDITOR"
alias qe="nvi"
alias sqe="sudo nvi"

# ls
alias ls="ls --color=auto --group-directories-first"
alias lsa="ls -lha"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# xbps
alias xr="sudo xbps-remove -Rof"
alias xu="sudo xbps-install -Su"
alias xc="sudo xbps-remove -ROo"

# other
alias hc="herbstclient"
alias buildsite="command rm -f docs/.files && ssg src docs \"chtc's site\" \"https://notchtc.github.io\""
