#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_normal_color '#002b36'
hc set frame_border_active_color '#b58900'
hc set frame_bg_normal_color '#073642'
hc set frame_bg_active_color '#b58900'
hc set frame_border_width 3
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_active_opacity 100
hc set frame_gap 0

hc attr theme.title_height 13
hc attr theme.title_font 'Iosevka Aile:pixelsize=12'  # example using Xft
hc attr theme.padding_top 3  # space below the title's baseline (i.e. text depth)
hc attr theme.active.color '#b58900'
hc attr theme.title_color '#002b36'
hc attr theme.normal.color '#002b36'
hc attr theme.urgent.color '#dc322f'
hc attr theme.normal.title_color '#839496'
hc attr theme.inner_width 0
hc attr theme.border_width 1
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.active.outer_width 0
hc attr theme.background_color '#002b36'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
