#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

bg=$(xrdb -get background)
bg_alt=$(xrdb -get color0)
fg=$(xrdb -get foreground)
fg_alt=$(xrdb -get color15)
focus=$(xrdb -get color3)
urgent=$(xrdb -get color1)

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_normal_color $bg
hc set frame_border_active_color $focus
hc set frame_bg_normal_color $bg_alt
hc set frame_bg_active_color $focus
hc set frame_border_width 0
hc set frame_border_inner_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 4
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

hc attr theme.title_height 0
hc attr theme.padding_top 0
hc attr theme.title_font 'Iosevka Aile:pixelsize=12'  # example using Xft
hc attr theme.active.color $focus
hc attr theme.title_color $bg
hc attr theme.normal.color $bg
hc attr theme.urgent.color $urgent
hc attr theme.normal.title_color $fg
hc attr theme.outer_width 0
hc attr theme.inner_width 0
hc attr theme.border_width 1
hc attr theme.floating.title_height 13
hc attr theme.floating.padding_top 3
hc attr theme.floating.border_width 2
hc attr theme.active.outer_width 0
hc attr theme.background_color $bg

hc watch tags.focus.frame_count
hc -i attribute_changed tags.focus.frame_count | while read; do
    hc or / and , compare tags.focus.frame_count = 1 , set frame_transparent_width 0 / set frame_transparent_width 2
done &

hc watch tags.focus.client_count
hc -i attribute_changed tags.focus.client_count | while read; do
    hc or / and , compare tags.focus.client_count = 1 , set_attr theme.border_width 0 / set_attr theme.border_width 1
done &
