xrdb -load ~/.config/x11/Xresources &
setxkbmap pl -option "caps:swapescape" &
pipewire &
pipewire-pulse &
dwmblocks &
hsetroot -cover ~/.local/share/wall.png &
dbus-launch --sh-syntax --exit-with-session dwm >/dev/null 2>&1
