xrdb -load ~/.config/x11/Xresources &
setxkbmap pl -option "caps:swapescape" &
pipewire &
pipewire-pulse &
hsetroot -cover ~/.local/share/wall.png &
unclutter &
connman-ui-gtk &
~/.config/polybar/launch.sh &
exec dbus-launch --exit-with-session herbstluftwm
