#!/bin/sh

# editor
alias e="$EDITOR"
alias se="doas $EDITOR"

# ls
alias ls="ls --color=auto --group-directories-first"
alias lsa="ls --color=auto -A --group-directories-first"
alias lsl="ls --color=auto -l --group-directories-first"
alias lsla="ls --color=auto -Al --group-directories-first"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# dnf
alias dni="doas dnf install"
alias dnr="doas dnf remove"
alias dnu="doas dnf upgrade"
alias dnc="doas dnf autoremove && doas dnf clean all"

# xbps
alias xr="doas xbps-remove -Rof"
alias xu="doas xbps-install -Su && doas xbps-remove -ROo"
alias xc="doas xbps-remove -ROo"

# other
adf() {
    asciidoctor-pdf -o - $1 | zathura -
}
smn() {
    apropos . | cut -d "(" -f 1 | cut -d "," -f 1 | fzf --multi -q "$1" --preview "man {1}" | xargs -ro man
}

alias sudo="doas"

alias buildsite="command rm -f docs/.files && ssg6 src docs \"chtc's site\" \"https://notchtc.github.io\""

alias cmus='screen -q -r -D cmus || screen -S cmus $(which --skip-alias cmus)'

alias ..="cd .."
alias ...="cd ../.."
