#!/bin/sh

# editor
alias e="$EDITOR"
alias se="doas $EDITOR"

# ls
alias ls="exa --group-directories-first"
alias lsa="exa -a --group-directories-first"
alias lsl="exa -a -l --git --group-directories-first"
alias lsla="exa -a -l --git --group-directories-first"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# dnf
alias dni="doas dnf install"
alias dnr="doas dnf remove"
alias dnu="doas dnf upgrade"
alias dnc="doas dnf autoremove && doas dnf clean all"

# xbps
alias xi="doas xbps-install"
alias xr="doas xbps-remove -Ro"
alias xu="doas xbps-install -Su"
alias xq="xbps-query"
alias xc="doas xbps-remove -ROo"

# other
adf() {
    asciidoctor-pdf -o - $1 | zathura -
}
smn() {
    apropos . | cut -d "(" -f 1 | cut -d "," -f 1 | fzf --multi -q "$1" --preview "man {1}" | xargs -ro man
}

alias bat="bat --theme ansi"
alias cmus="screen -q -r -D cmus || screen -S cmus $(which --skip-alias cmus)"
alias sudo="doas"

alias ..="cd .."

alias dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
