#!/bin/sh

# editor
alias e="$EDITOR"
alias se="sudo $EDITOR"

alias sudo="sudo $@"

# ls
alias ls="ls --color=auto --group-directories-first"
alias lsa="ls --color=auto -A --group-directories-first"
alias lsl="ls --color=auto -l --group-directories-first"
alias lsla="ls --color=auto -Al --group-directories-first"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# dnf
alias dni="sudo dnf install"
alias dnr="sudo dnf remove"
alias dnu="sudo dnf upgrade"
alias dnc="sudo dnf autoremove && doas dnf clean all"

# xbps
alias xr="sudo xbps-remove -Rof"
alias xu="sudo xbps-install -Su"
alias xc="sudo xbps-remove -ROo"

# other
adf() {
    asciidoctor-pdf -o - $1 | zathura -
}
smn() {
    apropos . | cut -d "(" -f 1 | cut -d "," -f 1 | fzf --multi -q "$1" --preview "man {1} 2>/dev/null" | xargs -ro -I{} man {}
}

alias buildsite="command rm -f docs/.files && ssg6 src docs \"chtc's site\" \"https://notchtc.github.io\""

alias ..="cd .."
alias ...="cd ../.."
