#!/bin/sh

# editor
alias e="$EDITOR"
alias se="doas $EDITOR"

# ls
alias ls="ls --color=auto --group-directories-first"
alias lsa="ls -lha"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# xbps
alias xr="doas xbps-remove -Rof"
alias xu="doas xbps-install -Su"
alias xc="doas xbps-remove -ROo"

# cd
alias ..2="cd ../../"
alias ..3="cd ../../../"
alias ..4="cd ../../../../"
alias ..5="cd ../../../../../"

# other
alias sudo="doas"
alias hc="herbstclient"
alias buildsite="command rm -f docs/.files && ssg src docs \"chtc's site\" \"https://notchtc.github.io\""
alias sx="startx $XINITRC"
